"""Updated the Document Model with Few Fields

Revision ID: 80cf63054337
Revises: 6c45997b79af
Create Date: 2026-07-19 14:54:42.829538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cf63054337'
down_revision: Union[str, Sequence[str], None] = '6c45997b79af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('extension', sa.String(length=10), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documents', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'extension')
    op.drop_column('documents', 'stored_filename')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
